function metric_scatter_3d(coord,z,clim,filename,cmap)
if ~exist('cmap','var')
    cmap = parula;
end

h.figure = figure('Color','w');
h.axes = axes;
h.sct = scatter3(coord(:,1),coord(:,2),coord(:,3),200,z,'.');
colormap(cmap)
xlabel('Gradient 1')
ylabel('Gradient 2')
zlabel('Gradient 3')
set(h.axes                                          , ...
    'PlotBoxAspectRatio'    , [1 1 1]               , ...
    'DataAspectRatio'       , [1 1 1]               , ...
    'XLim'                  , [-4 4]                , ...
    'XTick'                 , [-4 0 4]              , ...
    'YLim'                  , [-4 4]                , ...
    'YTick'                 , [-4 0 4]              , ...
    'ZLim'                  , [-4 4]                , ...
    'ZTick'                 , [-4 0 4]              , ...
    'FontName'              , 'DroidSans'           , ...
    'FontSize'              , 22                    );
caxis(clim)
grid on

export_fig(char(filename), '-m2', '-png');
close(gcf); 
end